# This file was generated by GoReleaser. DO NOT EDIT.
cask "aptscout" do
  name "aptscout"
  desc "Apartment availability tracker CLI"
  homepage "https://github.com/dotbrains/aptscout"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aptscout"

  on_macos do
    on_intel do
      url "https://github.com/dotbrains/aptscout/releases/download/v#{version}/aptscout_darwin_amd64.tar.gz"
      sha256 "3190d53ecdb85b253442bd3541d12ed8250dcfbd00aa773c0eb2cd356d845700"
    end
    on_arm do
      url "https://github.com/dotbrains/aptscout/releases/download/v#{version}/aptscout_darwin_arm64.tar.gz"
      sha256 "36b4e9937d06b649776b0a9a444a1b940eac65ce9386f0717d20c47ce4990326"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotbrains/aptscout/releases/download/v#{version}/aptscout_linux_amd64.tar.gz"
      sha256 "fc8349c94a8dcf55c97aaffc58027dcfab995d02de6fcbe2c0830f8db41ebd81"
    end
    on_arm do
      url "https://github.com/dotbrains/aptscout/releases/download/v#{version}/aptscout_linux_arm64.tar.gz"
      sha256 "b68587c1eab0e5f083d041f3b26293afb9a657a13a4ce4b479cf9a52f3a2b867"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aptscout"]
    end
  end

  # No zap stanza required
end
