# This file was generated by GoReleaser. DO NOT EDIT.
cask "aptscout" do
  name "aptscout"
  desc "Apartment availability tracker CLI"
  homepage "https://github.com/dotbrains/aptscout"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aptscout"

  on_macos do
    on_intel do
      url "https://github.com/dotbrains/aptscout/releases/download/v#{version}/aptscout_darwin_amd64.tar.gz"
      sha256 "932b91698869fb940846b788c111935211df92e6fc855a763e96683b5b2d6797"
    end
    on_arm do
      url "https://github.com/dotbrains/aptscout/releases/download/v#{version}/aptscout_darwin_arm64.tar.gz"
      sha256 "b67368d92611e3572fa5714b8e8d6820c5de9df5bb02e07967d7e562f4d26daa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotbrains/aptscout/releases/download/v#{version}/aptscout_linux_amd64.tar.gz"
      sha256 "a8d7c382accb2053e0dcc57b91afa56d3e829865136b1d61ba755992b0e86a2a"
    end
    on_arm do
      url "https://github.com/dotbrains/aptscout/releases/download/v#{version}/aptscout_linux_arm64.tar.gz"
      sha256 "4c2035d4d0cbc2ab787cae146bcc70a965681516225782bc8c4274f13ea0477d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aptscout"]
    end
  end

  # No zap stanza required
end
