# This file was generated by GoReleaser. DO NOT EDIT.
cask "awsw" do
  name "awsw"
  desc "Seamlessly switch between AWS SSO accounts and EKS contexts"
  homepage "https://github.com/dotbrains/awsw"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awsw"

  on_macos do
    on_intel do
      url "https://github.com/dotbrains/awsw/releases/download/v#{version}/awsw_darwin_amd64.tar.gz"
      sha256 "5ae5687d1545ba13517d4312e8555730cabee863662e88755787dd1b2da4d649"
    end
    on_arm do
      url "https://github.com/dotbrains/awsw/releases/download/v#{version}/awsw_darwin_arm64.tar.gz"
      sha256 "499e7071d28ee9a02f65352c38dd880380d1b9caf8487ae94fee955f60a97758"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotbrains/awsw/releases/download/v#{version}/awsw_linux_amd64.tar.gz"
      sha256 "2e010c9408d8068ed97255372ed2cfb780490af1e49dc2c7138d65f67ff060d7"
    end
    on_arm do
      url "https://github.com/dotbrains/awsw/releases/download/v#{version}/awsw_linux_arm64.tar.gz"
      sha256 "e684e23b297ab26262097e81e687fccc9c1b20f2dcc78bc965efb61edb09679e"
    end
  end

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/awsw"
    end
  end

  # No zap stanza required
end
