# This file was generated by GoReleaser. DO NOT EDIT.
cask "bellows" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "019c5d2ad3d3c47bb223b5dc16f615dbed76813852ec089d6d2bb844b9d692b9"
      url "https://github.com/dotbrains/bellows/releases/download/v#{version}/bellows_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3f32bf5618757e8dc4c8c356f45b07f97f9dfe52913c74b04106e9ece362ed6e"
      url "https://github.com/dotbrains/bellows/releases/download/v#{version}/bellows_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "90b0820b2233f4db780dad133e467f3ca8e472630ef0135a298cab8a4bad09f7"
      url "https://github.com/dotbrains/bellows/releases/download/v#{version}/bellows_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b0f32c4a15e6435befc6324021811a45d3d30bb8aeb029a6ce352f26f7ed2f44"
      url "https://github.com/dotbrains/bellows/releases/download/v#{version}/bellows_linux_arm64.tar.gz"
    end
  end

  name "bellows"
  desc "Run GitHub Actions locally before you push"
  homepage "https://github.com/dotbrains/bellows"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bellows"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bellows"]
    end
  end
  generate_completions_from_executable "bin/bellows", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
