# This file was generated by GoReleaser. DO NOT EDIT.
cask "bellows" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "6f39703a24dbe913de7d2df8d7f6b19614abd4a1faa3e2f8b7a45499fd68e559"
      url "https://github.com/dotbrains/bellows/releases/download/v#{version}/bellows_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7325ee64b03107f131dd1267f7ec0ac32ca12d8948ab0918dac7bf92b0613548"
      url "https://github.com/dotbrains/bellows/releases/download/v#{version}/bellows_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e85febc3a894c345e266f543e3b3cd10af8ee68a47cc01f2cd98fe091425e5ca"
      url "https://github.com/dotbrains/bellows/releases/download/v#{version}/bellows_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "603b84117e873aad8b639c170e718fad853c2d6f388947a96b9c9eb51de0e3f8"
      url "https://github.com/dotbrains/bellows/releases/download/v#{version}/bellows_linux_arm64.tar.gz"
    end
  end

  name "bellows"
  desc "Run GitHub Actions locally before you push"
  homepage "https://github.com/dotbrains/bellows"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bellows"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bellows"]
    end
  end

  # No zap stanza required

end
