# This file was generated by GoReleaser. DO NOT EDIT.
cask "bellows" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "f548883549fcd062c747d0198f1fa6f3b1f905420b2f2923e12e93ad00cfc3ed"
      url "https://github.com/dotbrains/bellows/releases/download/v#{version}/bellows_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1871f897c7300e17f6b0d3820d1398233c6d08ca17f960d05d1b0f45a119b3a4"
      url "https://github.com/dotbrains/bellows/releases/download/v#{version}/bellows_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5bca34668bc6af2101d09b836ba00402b6baa98c1da4232ee6e5ecb7e4352e59"
      url "https://github.com/dotbrains/bellows/releases/download/v#{version}/bellows_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "82f60671613ce61fe4505db9fbbcaeeca5a3e163d2806335f629d73b7a2f55bc"
      url "https://github.com/dotbrains/bellows/releases/download/v#{version}/bellows_linux_arm64.tar.gz"
    end
  end

  name "bellows"
  desc "Run GitHub Actions locally before you push"
  homepage "https://github.com/dotbrains/bellows"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bellows"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bellows"]
    end
  end
  generate_completions_from_executable "bin/bellows",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
