# This file was generated by GoReleaser. DO NOT EDIT.
cask "distill" do
  name "distill"
  desc "AI-powered knowledge compactor for agents"
  homepage "https://github.com/dotbrains/distill"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "distill"

  on_macos do
    on_intel do
      url "https://github.com/dotbrains/distill/releases/download/v#{version}/distill_darwin_amd64.tar.gz"
      sha256 "10e1c2deea7a6f5b09c243a22ea5193eea103ffe7f0b48dd08b6b5c64fe3be8e"
    end
    on_arm do
      url "https://github.com/dotbrains/distill/releases/download/v#{version}/distill_darwin_arm64.tar.gz"
      sha256 "5024728d1da2a677ef6e86eb1e92496d38aecf289486ed338904556526fcb4e5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotbrains/distill/releases/download/v#{version}/distill_linux_amd64.tar.gz"
      sha256 "0e1f26a8d7a71c4b90dee8d34b553d36689c9b8067e6bfcc287b27aed4a1f40d"
    end
    on_arm do
      url "https://github.com/dotbrains/distill/releases/download/v#{version}/distill_linux_arm64.tar.gz"
      sha256 "3b96ae3cee0ca777ccef25b5dc952aa56a335e69f07ec91ed6e9c24ee343cf31"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/distill"]
    end
  end

  # No zap stanza required
end
