# This file was generated by GoReleaser. DO NOT EDIT.
cask "glimpse" do
  name "glimpse"
  desc "GitHub-style git diff viewer CLI"
  homepage "https://github.com/dotbrains/glimpse"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glimpse"

  on_macos do
    on_intel do
      url "https://github.com/dotbrains/glimpse/releases/download/v#{version}/glimpse_darwin_amd64.tar.gz"
      sha256 "3b77c2645018b381b25c80eb859cc8b662ff15dcbeca89e7a46ca2ab1680acb7"
    end
    on_arm do
      url "https://github.com/dotbrains/glimpse/releases/download/v#{version}/glimpse_darwin_arm64.tar.gz"
      sha256 "961578cbc484cc2ecfbd778a674aa4bda97fa6eea95c9007ba7b3cf76f54c077"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotbrains/glimpse/releases/download/v#{version}/glimpse_linux_amd64.tar.gz"
      sha256 "34020c6106d79ddf213ae3d7dcee3bacafe8d4b2eede9b15d52d54a2f9947890"
    end
    on_arm do
      url "https://github.com/dotbrains/glimpse/releases/download/v#{version}/glimpse_linux_arm64.tar.gz"
      sha256 "3afa19298a3b255f726e8ff6f67623fdaaea9579b9b9706b5d9409d96a28706f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glimpse"]
    end
  end

  # No zap stanza required
end
