# This file was generated by GoReleaser. DO NOT EDIT.
cask "prr" do
  name "prr"
  desc "AI-powered PR code review CLI"
  homepage "https://github.com/dotbrains/prr"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prr"

  on_macos do
    on_intel do
      url "https://github.com/dotbrains/prr/releases/download/v#{version}/prr_darwin_amd64.tar.gz"
      sha256 "3c40a6fd413c32d960e11181d09cb5e8c421371ccd73e8ab09b02b8f04e63251"
    end
    on_arm do
      url "https://github.com/dotbrains/prr/releases/download/v#{version}/prr_darwin_arm64.tar.gz"
      sha256 "0e37102727c6508ca6084296db617883d5d1acbab80d2c0a83263f9c63cd1104"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotbrains/prr/releases/download/v#{version}/prr_linux_amd64.tar.gz"
      sha256 "6729e0e6e51b350dd237bb6afcb5537e80e599d0f11afcbb6d8fd643c750846e"
    end
    on_arm do
      url "https://github.com/dotbrains/prr/releases/download/v#{version}/prr_linux_arm64.tar.gz"
      sha256 "bcb14f410de73e07aea8fc179a2df0096cde855faf2a77373a57901a6cbcda39"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prr"]
    end
  end

  # No zap stanza required
end
