# This file was generated by GoReleaser. DO NOT EDIT.
cask "prr" do
  name "prr"
  desc "AI-powered PR code review CLI"
  homepage "https://github.com/dotbrains/prr"
  version "0.9.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prr"

  on_macos do
    on_intel do
      url "https://github.com/dotbrains/prr/releases/download/v#{version}/prr_darwin_amd64.tar.gz"
      sha256 "fab31aa0ae19f8e241307d3a17f7cb3377f580af6d2fa157e689d112fc9f4215"
    end
    on_arm do
      url "https://github.com/dotbrains/prr/releases/download/v#{version}/prr_darwin_arm64.tar.gz"
      sha256 "635b39c56f80723becfefb94800968b067954cfb1ac354dfa1db750c64bfcb34"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotbrains/prr/releases/download/v#{version}/prr_linux_amd64.tar.gz"
      sha256 "b704ce6eaa79edf2338090ab7070669d259861f28d265cb96effa71f54b24385"
    end
    on_arm do
      url "https://github.com/dotbrains/prr/releases/download/v#{version}/prr_linux_arm64.tar.gz"
      sha256 "e2c0f0266a4a174cdb224c0ebe9dfad9dad8ccdcf9ebc41b174564c38df323f4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prr"]
    end
  end

  # No zap stanza required
end
