# This file was generated by GoReleaser. DO NOT EDIT.
cask "prr" do
  name "prr"
  desc "AI-powered PR code review CLI"
  homepage "https://github.com/dotbrains/prr"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prr"

  on_macos do
    on_intel do
      url "https://github.com/dotbrains/prr/releases/download/v#{version}/prr_darwin_amd64.tar.gz"
      sha256 "e35030e1e137df2e51d113fa8c5303ff23cb57c330b0b477c972eb73f5deecf3"
    end
    on_arm do
      url "https://github.com/dotbrains/prr/releases/download/v#{version}/prr_darwin_arm64.tar.gz"
      sha256 "3497f3e1289999362cc47a71d4994f00da9dd8aa377918fac05ffe94da15fa50"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dotbrains/prr/releases/download/v#{version}/prr_linux_amd64.tar.gz"
      sha256 "4f1bc1d15970fd774a35897e6b2b97d2f8ea0f746bf94707aa382aa84f1ed0af"
    end
    on_arm do
      url "https://github.com/dotbrains/prr/releases/download/v#{version}/prr_linux_arm64.tar.gz"
      sha256 "612f8e884689422f04dcc21a49d54f086ab61352b428c83c6a013a8cfa5f528c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/prr"]
    end
  end

  # No zap stanza required
end
