# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhIdentity < Formula
  desc "Multi-account GitHub identity management — automatic context-based account switching and per-directory identity binding."
  homepage "https://github.com/dotbrains/gh-identity"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dotbrains/gh-identity/releases/download/v0.2.0/gh-identity_0.2.0_darwin_amd64.tar.gz"
      sha256 "393765329d90f2b674ec0a015e696df8153cbb55b5a4387b0324efd0f627510d"

      define_method(:install) do
        bin.install "gh-identity"
        bin.install "gh-identity-hook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dotbrains/gh-identity/releases/download/v0.2.0/gh-identity_0.2.0_darwin_arm64.tar.gz"
      sha256 "0e0546b8d9705e9f11d571105a0e3439d04a7e2140d064408508128781a8d106"

      define_method(:install) do
        bin.install "gh-identity"
        bin.install "gh-identity-hook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotbrains/gh-identity/releases/download/v0.2.0/gh-identity_0.2.0_linux_amd64.tar.gz"
      sha256 "9def30aa4c021915b4bf42988becdbe8b10c37d28bba60551a7fc7bdb0fc93ed"
      define_method(:install) do
        bin.install "gh-identity"
        bin.install "gh-identity-hook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotbrains/gh-identity/releases/download/v0.2.0/gh-identity_0.2.0_linux_arm64.tar.gz"
      sha256 "d737a9ee9ff53b380111c2b2b3ac74d17c4988eb4855624146f15e95750ead9b"
      define_method(:install) do
        bin.install "gh-identity"
        bin.install "gh-identity-hook"
      end
    end
  end

  test do
    system "#{bin}/gh-identity", "--help"
  end
end
