# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhIdentity < Formula
  desc "Multi-account GitHub identity management — automatic context-based account switching and per-directory identity binding."
  homepage "https://github.com/dotbrains/gh-identity"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dotbrains/gh-identity/releases/download/v0.4.0/gh-identity_0.4.0_darwin_amd64.tar.gz"
      sha256 "70464c4e638827845a75c5329d494484531111d1f4f0cb674911f0b223a3457e"

      define_method(:install) do
        bin.install "gh-identity"
        bin.install "gh-identity-hook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dotbrains/gh-identity/releases/download/v0.4.0/gh-identity_0.4.0_darwin_arm64.tar.gz"
      sha256 "4634660bba54a168e511f081e7b523fc5a2ac8bade531c00dffd57d6a3431a52"

      define_method(:install) do
        bin.install "gh-identity"
        bin.install "gh-identity-hook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotbrains/gh-identity/releases/download/v0.4.0/gh-identity_0.4.0_linux_amd64.tar.gz"
      sha256 "1552ca96e89603e1d266aaac27f2698660127aa5e6449636f09ee8e6e68b9ef8"
      define_method(:install) do
        bin.install "gh-identity"
        bin.install "gh-identity-hook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotbrains/gh-identity/releases/download/v0.4.0/gh-identity_0.4.0_linux_arm64.tar.gz"
      sha256 "ddd56fd21ba1e9c546939410be8d2d5e1c6270ac0453d601be03e9aecc2fb363"
      define_method(:install) do
        bin.install "gh-identity"
        bin.install "gh-identity-hook"
      end
    end
  end

  test do
    system "#{bin}/gh-identity", "--help"
  end
end
