# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prr < Formula
  desc "AI-powered PR code review CLI"
  homepage "https://github.com/dotbrains/prr"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dotbrains/prr/releases/download/v0.1.0/prr_darwin_amd64.tar.gz"
      sha256 "0c1d1d2b4f05d9bf0babf0df839505f1a4687b5789f60f5e2d75afdc2b656a65"

      define_method(:install) do
        bin.install "prr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dotbrains/prr/releases/download/v0.1.0/prr_darwin_arm64.tar.gz"
      sha256 "f91239048a23f58f3d23d6b75073750cb42b3c0c90d858831c67122905a0f81d"

      define_method(:install) do
        bin.install "prr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotbrains/prr/releases/download/v0.1.0/prr_linux_amd64.tar.gz"
      sha256 "09985b7ba698a23bb2766c4b7ec383b533ae4aa062db7fc0bfdbf551fb47c5d7"
      define_method(:install) do
        bin.install "prr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotbrains/prr/releases/download/v0.1.0/prr_linux_arm64.tar.gz"
      sha256 "2cbb342e18509974b945e8c671c85fe20a386829a9df5edae9716e6d82aecfea"
      define_method(:install) do
        bin.install "prr"
      end
    end
  end

  test do
    system "#{bin}/prr", "--version"
  end
end
